### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by imoyy** [cyl528656253/h610m_maxsun_5500xt_12100F#1]
请问oc版本是多少，不知道版本不好自己微调。
希望感知我，感谢

**Comment by jackyiero** [comment]
我用了没有声音

**Comment by cyl528656253** [comment]
> 请问oc版本是多少，不知道版本不好自己微调。 希望感知我，感谢

估计要微调下，版本应该是0.8.2

**Comment by cyl528656253** [comment]
> 我用了没有声音

应该是需要定制usb的，不然有些usb口用不了

**Comment by cyl528656253** [comment]
> 请问oc版本是多少，不知道版本不好自己微调。 希望感知我，感谢
应该是8.5版本的
